apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-devops-project
  region: us-east-1
  version: "1.31"

iam:
  withOIDC: true  # ← habilita OIDC automáticamente (paso 1 manual eliminado)

addons:
  - name: aws-ebs-csi-driver  # ← instala el driver automáticamente
    wellKnownPolicies:
      ebsCSIController: true  # ← crea el IAM role automáticamente (paso 2 y 3 eliminados)

  - name: vpc-cni                   
    wellKnownPolicies:
      imageBuilder: false
    configurationValues: |
      env:
        ENABLE_PREFIX_DELEGATION: "true"
        WARM_PREFIX_TARGET: "1"

managedNodeGroups:

  - name: app-nodes
    instanceType: t3.small
    minSize: 1
    maxSize: 5
    desiredCapacity: 2
    labels:
      role: app

  - name: db-nodes
    instanceType: t3.small
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    labels:
      role: db
    taints:
      - key: workload
        value: database
        effect: NoSchedule
