replicaCount: 1

image:
  repository: nginx
  tag: "alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  host: ""

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

nodeAffinity:
  enabled: true

metrics:
  enabled: true

alerts:
  enabled: true
  errorRateThreshold: 0.05    # 5% error rate
  latencyThreshold: 1.0       # 1 second latancy p95