apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: {{ .Release.Namespace }}
  labels:
    app: external-dns
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.iamRoleArn }}