apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            # This is the ESO controller's service account, which has your
            # IRSA role annotation (arn:aws:iam::067614922294:role/eks-devops-eso-role)
            name: external-secrets
            namespace: external-secrets
