{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-db-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Release.Name }}-postgresql   # nombre que genera Bitnami
  updatePolicy:
    updateMode: "Off"
{{- end }}