name: CI — Build and Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-validate:
    name: Lint Helm Charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Lint all charts
        run: |
          helm lint charts/frontend
          helm lint charts/backend
          helm dependency update charts/database
          helm lint charts/database

      - name: Validate helmfile
        run: |
          wget -q https://github.com/helmfile/helmfile/releases/download/v1.4.4/helmfile_1.4.4_linux_amd64.tar.gz
          tar -zxf helmfile_1.4.4_linux_amd64.tar.gz
          sudo mv helmfile /usr/local/bin/
          helm plugin install https://github.com/databus23/helm-diff
          helmfile lint
